name = "HyperGraphs"
uuid = "e54fe45a-379a-431d-91b1-83d23201f60f"
authors = ["Leo Diaz <diazl@unimelb.edu.au>"]
version = "0.2.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SimpleTraits = "699a6c99-e7fa-54fc-8d76-47d257e15c1d"
